name: Publish SNAP package to NPM

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
        continue-on-error: true

      - run: yarn build
        working-directory: packages/snap
        continue-on-error: true

      - run: yarn npm publish
        working-directory: packages/snap
        env:
          NODE_AUTH_TOKEN: ${{secrets.POLYGONID_NPM_PUBLISH_TOKEN}}
